{"name": "FakeValuesService_addPathTest", "status": "assertion error", "error": "[INFO] Scanning for projects...\n[INFO] Inspecting build with total of 1 modules...\n[INFO] Installing Nexus Staging features:\n[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin\n[INFO] \n[INFO] ----------------------< net.datafaker:datafaker >-----------------------\n[INFO] Building Datafaker 2.4.1-SNAPSHOT\n[INFO]   from pom.xml\n[INFO] --------------------------------[ jar ]---------------------------------\n[INFO] \n[INFO] --- enforcer:3.5.0:enforce (enforce-maven) @ datafaker ---\n[INFO] Rule 0: org.apache.maven.enforcer.rules.version.RequireJavaVersion passed\n[INFO] Rule 1: org.apache.maven.enforcer.rules.version.RequireMavenVersion passed\n[INFO] \n[INFO] --- spotless:2.43.0:check (spotless-check) @ datafaker ---\n[INFO] Spotless.Java is keeping 663 files clean - 0 needs changes to be clean, 0 were already clean, 663 were skipped because caching determined they were already clean\n[INFO] Spotless.Yaml is keeping 254 files clean - 0 needs changes to be clean, 0 were already clean, 254 were skipped because caching determined they were already clean\n[INFO] \n[INFO] --- jacoco:0.8.12:prepare-agent (default) @ datafaker ---\n[INFO] argLine set to -javaagent:/home/zhangzhe/.m2/repository/org/jacoco/org.jacoco.agent/0.8.12/org.jacoco.agent-0.8.12-runtime.jar=destfile=/home/zhangzhe/fuzzing-repo/targets/datafaker/target/jacoco.exec\n[INFO] \n[INFO] --- resources:3.3.1:resources (default-resources) @ datafaker ---\n[INFO] Copying 340 resources from src/main/resources to target/classes\n[INFO] \n[INFO] --- kotlin:2.0.20:compile (compile) @ datafaker ---\n[INFO] No sources to compile\n[INFO] \n[INFO] --- compiler:3.13.0:compile (compile) @ datafaker ---\n[INFO] Nothing to compile - all classes are up to date.\n[INFO] \n[INFO] --- resources:3.3.1:testResources (default-testResources) @ datafaker ---\n[INFO] Copying 5 resources from src/test/resources to target/test-classes\n[INFO] \n[INFO] --- kotlin:2.0.20:test-compile (test-compile) @ datafaker ---\n[INFO] \n[INFO] --- compiler:3.13.0:testCompile (testCompile) @ datafaker ---\n[INFO] Nothing to compile - all classes are up to date.\n[INFO] \n[INFO] --- surefire:3.5.0:test (default-test) @ datafaker ---\n[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider\n[INFO] \n[INFO] -------------------------------------------------------\n[INFO]  T E S T S\n[INFO] -------------------------------------------------------\n[INFO] Running net.datafaker.service.FakeValuesService_addPathTest\n[ERROR] Tests run: 6, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.177 s <<< FAILURE! -- in net.datafaker.service.FakeValuesService_addPathTest\n[ERROR] net.datafaker.service.FakeValuesService_addPathTest.testAddPathMalformedURL -- Time elapsed: 0.083 s <<< FAILURE!\norg.opentest4j.AssertionFailedError: expected: <true> but was: <false>\n\tat org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)\n\tat org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)\n\tat org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)\n\tat org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)\n\tat org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)\n\tat org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:183)\n\tat net.datafaker.service.FakeValuesService_addPathTest.testAddPathMalformedURL(FakeValuesService_addPathTest.java:66)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)\n\n[ERROR] net.datafaker.service.FakeValuesService_addPathTest.testAddPathSuccess -- Time elapsed: 0.084 s <<< FAILURE!\norg.opentest4j.AssertionFailedError: Unexpected exception thrown: java.lang.IllegalArgumentException: Path should be an existing readable file: \"src/test/resources/testfile.txt\"\n\tat org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)\n\tat org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:84)\n\tat org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:53)\n\tat org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:36)\n\tat org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3199)\n\tat net.datafaker.service.FakeValuesService_addPathTest.testAddPathSuccess(FakeValuesService_addPathTest.java:26)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)\nCaused by: java.lang.IllegalArgumentException: Path should be an existing readable file: \"src/test/resources/testfile.txt\"\n\tat net.datafaker.service.FakeValuesService.addPath(FakeValuesService.java:109)\n\tat net.datafaker.service.FakeValuesService_addPathTest.lambda$0(FakeValuesService_addPathTest.java:26)\n\tat org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:49)\n\t... 9 more\n\n[INFO] \n[INFO] Results:\n[INFO] \n[ERROR] Failures: \n[ERROR]   FakeValuesService_addPathTest.testAddPathMalformedURL:66 expected: <true> but was: <false>\n[ERROR]   FakeValuesService_addPathTest.testAddPathSuccess:26 Unexpected exception thrown: java.lang.IllegalArgumentException: Path should be an existing readable file: \"src/test/resources/testfile.txt\"\n[INFO] \n[ERROR] Tests run: 6, Failures: 2, Errors: 0, Skipped: 0\n[INFO] \n[INFO] ------------------------------------------------------------------------\n[INFO] BUILD FAILURE\n[INFO] ------------------------------------------------------------------------\n[INFO] Total time:  8.353 s\n[INFO] Finished at: 2024-10-01T19:20:26+08:00\n[INFO] ------------------------------------------------------------------------\n[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.5.0:test (default-test) on project datafaker: There are test failures.\n[ERROR] \n[ERROR] Please refer to /home/zhangzhe/fuzzing-repo/targets/datafaker/target/surefire-reports for the individual test results.\n[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.\n[ERROR] -> [Help 1]\n[ERROR] \n[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.\n[ERROR] Re-run Maven using the -X switch to enable full debug logging.\n[ERROR] \n[ERROR] For more information about the errors and possible solutions, please read the following articles:\n[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException\n"}